default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  host: db
  database: works_development
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

test:
  <<: *default
  host: db 
  database: works_test
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

production:
  <<: *default
  database: <%= Rails.application.credentials.config.dig(:psql, :database) %>
  host: <%= Rails.application.credentials.config.dig(:psql, :host) %>
  username: <%= Rails.application.credentials.config.dig(:psql, :user) %>
  password: <%= Rails.application.credentials.config.dig(:psql, :password) %>
